version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_ID=root
      - JENKINS_ADMIN_PASSWORD=root
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./.:/var/jenkins_home/data

volumes:
  jenkins_home:
